// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mysbibaxtfvsnksqodia.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im15c2JpYmF4dGZ2c25rc3FvZGlhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0MjE1OTEsImV4cCI6MjA2OTk5NzU5MX0.V7cpxJlX7AYAd46WLQN35LZ3soP3Vs8P_x58IPZ5xHU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});